services:
  # Zookeeper est là pour faire une mémoire partagée
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Définition de mon broker KAFKA
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
